### ISSUE TITLE
Deprecated functions in Gutenberg

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#541]
**Describe the bug**
Update the functions

**Expected behavior**
![image](https://user-images.githubusercontent.com/44024114/112630477-4ca60f80-8e3e-11eb-98f6-f72990d15a40.png)

**Comment by giucu91** [comment]
I think this is fixed. we need to check.

**Comment by razvanaldea89** [comment]
Not fixed yet, still can be found in : ModulaGallerySearch.js, edit.js and inspector.js, all in assets/src/js/components
