### ISSUE TITLE
Upsells are not removed based on license key

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#893]
**Describe the bug**
With business license these still appear:
![image (2)](https://github.com/WPChill/modula-lite/assets/44024114/369d753d-1641-42dc-8f58-b41c1f28fa52)

**To Reproduce**
1. Active higher license
2. Go to settings
3. See upsells

**Expected behavior**
Upsells for the extensions that are contained in the licensed package should not be shown

**Comment by giucu91** [comment]
Check if this is not related with our christmas campaign.

**Comment by TeoAlex** [comment]
Fixed by https://github.com/WPChill/modula-pro/issues/603

**Comment by cristinnaiulia** [comment]
With business license the upsells still appear.
![Screenshot 2024-04-25 120508](https://github.com/WPChill/modula-lite/assets/63049546/b1afceb7-c8c0-4f60-8b4b-27253769bece)

**Comment by cristeacosmin** [comment]
![image](https://github.com/WPChill/modula-lite/assets/10389279/0d86e21c-a113-4d9d-8499-7447778907a4)

![image](https://github.com/WPChill/modula-lite/assets/10389279/2afb4e35-09c3-4b0d-9eb9-17b45b5135a5)

Differences between these 2 tabs
